// File generated by flutterfire_cli.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// `FirebaseOptions` when running on any platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEaJPPGVRb9Fv3pP0v6vJ0v6vJ0v6vJ0v',
    authDomain: 'jain-app.firebaseapp.com',
    projectId: 'jain-app',
    storageBucket: 'jain-app.appspot.com',
    messagingSenderId: '123456789',
    appId: '1:123456789:web:abcdefghijklmnop',
    measurementId: 'G-XXXXXXXXXX',
  );
}
